# Generated by Django 2.2.18 on 2021-06-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_auto_20210529_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sermon',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
